# Generated by Django 5.0.8 on 2024-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('Bhandara', 'Bhandara'), ('Langarh', 'Langarh')], default='Bhandara', max_length=100),
        ),
    ]
