services:
  docs:
    image: free_food_finder_local_docs
    container_name: free_food_finder_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./free_food_finder:/app/free_food_finder:z
    ports:
      - '9000:9000'
    command: /start-docs
